name: $(SemVer)

variables:
  BuildRev: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  SemVer: $[ variables['Build.SourceBranchName'] ]
  InfoVer: $(Build.SourceVersion)

trigger:
  batch: true
  branches:
    include:
    - refs/tags/*

pr: none

stages:
- template: az-templates/stage-build.yml
- tamplate: az-templates/stage-test.yml
- template: az-templates/stage-deploy.yml
