name: $(SemVer)

variables:
  BuildRev: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  SemVer: $[ variables['Build.SourceBranchName'] ]
  InfoVer: $(Build.SourceVersion)

trigger:
  branches:
    exclude:
    - '*'
  tags:
    include:
    - '*'

pr: none

stages:
- template: az-templates/stage-build.yml
- template: az-templates/stage-test.yml
- template: az-templates/stage-deploy.yml
