stages:
- stage: Build
  jobs:
  - job: BuildBinaries
    displayName: Build solution
    timeoutInMinutes: 10
    strategy:
      matrix:
        linux:
          imageName: ubuntu-18.04
        mac:
          imageName: macos-10.15
        windows:
          imageName: windows-2019

    pool:
      vmImage: $(imageName)

    steps:
    - task: PowerShell@2
      displayName: Print environment
      inputs:
        targetType: 'inline'
        script: |
          gci ENV:
          $HOME
          $PWD
        pwsh: true
    
    - task: PowerShell@2 # Restore frequently fails when using it
      displayName: Disable Nuget source "Microsoft Visual Studio Offline Packages"
      condition: eq(variables['Agent.OS'], 'Windows_NT') # Not an issue on Linux and MacOS obviously
      inputs:
        targetType: 'inline'
        script: dotnet nuget disable source "Microsoft Visual Studio Offline Packages"
        pwsh: true

    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: build
        projects: src/*.sln
        arguments: >-
          --configuration $(BuildConfiguration)
          --no-incremental
          --nologo
          -p:TreatWarningsAsErrors=true
          -p:Version=$(SemVer)
          -p:InformationalVersion=$(InfoVer)

    - task: PublishPipelineArtifact@1
      displayName: Publish binaries for use in dependent jobs
      condition: eq(variables['Agent.OS'], 'Windows_NT') # We only use the binaries from the Windows built, it produces net452 and netstandard1.6 DLLs
      inputs:
        targetpath: ./
        artifactname: binaries

  - job: UnitTestBinaries
    dependsOn: BuildBinaries
    displayName: Run unit tests
    timeoutInMinutes: 10
    strategy:
      matrix:
        linux-netcore:
          imageName: ubuntu-18.04
          targetFrameworkMoniker: netcoreapp3.1
        mac-netcore:
          imageName: macos-10.15
          targetFrameworkMoniker: netcoreapp3.1
        windows-netcore:
          imageName: windows-2019
          targetFrameworkMoniker: netcoreapp3.1
        windows-nextfx:
          imageName: windows-2019
          targetFrameworkMoniker: net452
    pool:
      vmImage: $(imageName)

    steps:
      - checkout: none

      - task: DownloadPipelineArtifact@2
        inputs:
          targetpath: ./
          artifactname: binaries

      - task: DotNetCoreCLI@2
        displayName: Run unit tests
        inputs:
          command: test
          projects: src/Tests/UnitTests/bin/$(BuildConfiguration)/$(targetFrameworkMoniker)/UnitTests.dll
          arguments: --framework $(targetFrameworkMoniker) --nologo
          testRunTitle: UnitTests $(imageName) $(targetFrameworkMoniker)
