stages:
- stage: Deploy
  condition: and (succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ))
  dependsOn: Test
  jobs:
  - deployment: DeployArtifacts
    environment: Prod
    displayName: Deploys artifacts
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 5
    strategy: 
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            displayName: Download Nuget artifacts
            inputs:
              targetpath: ./
              patterns: |
                package/**/*
              artifactname: binaries

          - task: CmdLine@2
            displayName: Push Nuget artifacts
            inputs:
              script: >-
                dotnet nuget push
                -s https://api.nuget.org/v3/index.json
                -k $(NUGET_TOKEN)
                ./package/*
              env:
                NUGET_TOKEN: $(nuget_org_push_new_versions)
