stages:
- stage: Build
  jobs:
  - template: platform-dependent-job.yml
    parameters:
      jobTitle: BuildBinaries
      displayName: Build solution
      matrix:
        linux:
          imageName: ubuntu-18.04
        mac:
          imageName: macos-10.15
        windows:
          imageName: windows-2019
      steps:
      - task: CmdLine@2 # Restore frequently fails when using it
        displayName: Disable Nuget source "Microsoft Visual Studio Offline Packages"
        condition: eq(variables['Agent.OS'], 'Windows_NT') # Not an issue on Linux and MacOS obviously
        inputs:
          script: dotnet nuget disable source "Microsoft Visual Studio Offline Packages"

      - task: CmdLine@2
        displayName: Build solution
        inputs:
          script: >-
            dotnet build ./src/NATS.sln
            --configuration Release
            --no-incremental
            -p:TreatWarningsAsErrors=true
            -p:Version=$(SemVer)

      - task: CmdLine@2
        displayName: Package NATS.Client
        inputs:
          script: >-
            dotnet pack ./src/NATS.Client/
            --configuration Release
            --no-build
            --include-symbols
            --output ./package
            -p:Version=$(SemVer)

      - task: PublishPipelineArtifact@1
        displayName: Publish binaries for use in dependent jobs
        condition: eq(variables['Agent.OS'], 'Windows_NT') # We only use the binaries from the Windows built, it produces net46 and netstandard1.6 DLLs
        inputs:
          targetpath: ./
          artifactname: binaries
