stages:
- stage: Build
  jobs:
  - template: platform-dependent-job.yml
    parameters:
      jobTitle: BuildBinaries
      displayName: Build solution
      matrix:
        linux:
          imageName: ubuntu-18.04
        mac:
          imageName: macos-10.15
        windows:
          imageName: windows-2019
      steps:
      - task: CmdLine@2 # Restore frequently fails when using it
        displayName: Disable Nuget source "Microsoft Visual Studio Offline Packages"
        condition: eq(variables['Agent.OS'], 'Windows_NT') # Not an issue on Linux and MacOS obviously
        inputs:
          script: dotnet nuget disable source "Microsoft Visual Studio Offline Packages"

      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: build
          projects: src/*.sln
          arguments: >-
            --configuration Release
            --no-incremental
            -p:TreatWarningsAsErrors=true
            -p:Version=$(SemVer)
            -p:InformationalVersion=$(InfoVer)

      - task: DotNetCoreCLI@2
        displayName: Package NATS.Client/
        inputs:
          command: pack
          projects: src/NATS.Client/
          arguments: >-
            --configuration Release
            --no-build
            --include-symbols
            --output ./package
            -p:Version=$(SemVer)
            -p:InformationalVersion=$(InfoVer)

      - task: PublishPipelineArtifact@1
        displayName: Publish binaries for use in dependent jobs
        condition: eq(variables['Agent.OS'], 'Windows_NT') # We only use the binaries from the Windows built, it produces net46 and netstandard1.6 DLLs
        inputs:
          targetpath: ./
          artifactname: binaries

  - template: platform-dependent-job.yml
    parameters:
      jobTitle: UnitTestBinaries
      displayName: Run unit tests
      dependsOn: BuildBinaries
      steps:
      - template: steps-test.yml
        parameters:
          testProject: UnitTests

  - template: platform-dependent-job.yml
    parameters:
      jobTitle: IntegrationTestBinaries
      displayName: Run integration tests
      dependsOn: BuildBinaries
      steps:
      - template: steps-test.yml
        parameters:
          testProject: IntegrationTests
          mayFailOn: Darwin
          preTestSteps:
          - template: install-nats-server.yml
