stages:
- stage: Build
  jobs:
  - job: BuildArtifacts
    displayName: Builds binaries
    timeoutInMinutes: 10
    strategy:
      matrix:
        linux:
          imageName: ubuntu-18.04
        mac:
          imageName: macos-10.15
        windows:
          imageName: windows-2019

    pool:
      vmImage: $(imageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: build
        projects: src/*.sln
        arguments: '-c $(BuildConfiguration) --no-incremental --nologo -p:TreatWarningsAsErrors=true -p:Version=$(SemVer) -p:InformationalVersion=$(InfoVer)'

    - task: PublishPipelineArtifact@1
      displayName: Publish binaries for use in following jobs
      condition: eq(variables['Agent.OS'], 'Windows_NT')
      inputs:
        targetpath: ./
        artifactname: binaries
